language: ruby
rvm: "2.2.0"

before_install:
  - gem install bundler

install: bundle install --retry=3 --jobs=3 --no-cache

before_script:
  - bundle exec rake db:create:all
  - bundle exec rake db:migrate

script:
  - bundle exec rspec --format progress
