language: ruby
rvm: "2.2.0"

before_install:
  - rm -Rf /home/travis/.rvm/gems/ruby-2.2.0/cache/bundler/git/feedjira-272b56445a1b41a2e5477c8f18f9622b9ee8de6b
  - gem install bundler
  - bundle clean

before_script:
  - bundle exec rake db:create:all
  - bundle exec rake db:migrate

script:
  - bundle exec rspec --format progress
