language: ruby
rvm: "2.1.0"

before_install:
  - gem install bundler

before_script:
  - bundle exec rake db:create:all
  - bundle exec rake db:migrate

script:
  - bundle exec rspec --format progress
